"""
Cheating Detection Service
Three signals combined into a confidence score:

1. Behavioral signals  — response latency, speech pace, pause patterns
2. Perplexity scoring  — LLM rates how "surprising" each sentence is
3. Semantic similarity — compare against known answer templates (Month 3+)

Note: No scipy/numpy dependency — pure Python + Claude API only.
"""
import re
from typing import Optional
from app.core.config import settings

try:
    import anthropic
    _client = anthropic.Anthropic(api_key=settings.ANTHROPIC_API_KEY) if settings.ANTHROPIC_API_KEY else None
except ImportError:
    _client = None


# ── Signal 1: Behavioral ──────────────────────────────────────────────────────

def behavioral_score(transcript: str, duration_seconds: int, question_text: str) -> dict:
    """
    Returns a suspicion score (0-1) based on:
    - Words per second (natural speech = 2-3 wps; reading = 3.5+ wps)
    - Filler word presence (um, uh, like, you know)
    - Perfect sentence starts (AI tends to start with "Certainly", "Of course", etc.)
    - Self-corrections ("actually, let me rephrase...")
    """
    words = transcript.split()
    word_count = len(words)
    wps = word_count / max(duration_seconds, 1)

    flags = []
    suspicion = 0.0

    # Reading speed check
    if wps > 3.8:
        flags.append(f"High speech rate ({wps:.1f} words/sec — typical reading pace)")
        suspicion += 0.3

    # Filler word check (absence is suspicious in long answers)
    filler_pattern = r"\b(um|uh|like|you know|i mean|sort of|kind of|basically|actually)\b"
    filler_count = len(re.findall(filler_pattern, transcript.lower()))
    if word_count > 80 and filler_count == 0:
        flags.append("No natural filler words in a long response")
        suspicion += 0.2

    # AI-style opening
    ai_openers = ["certainly", "of course", "absolutely", "great question", "i'd be happy to"]
    if any(transcript.lower().startswith(o) for o in ai_openers):
        flags.append("Response starts with AI-style affirmation")
        suspicion += 0.25

    # Unusually perfect structure
    sentences = re.split(r'[.!?]+', transcript.strip())
    sentences = [s.strip() for s in sentences if len(s.strip()) > 5]
    if len(sentences) >= 4:
        perfect = sum(1 for s in sentences if s and s[0].isupper())
        if perfect / len(sentences) > 0.95:
            flags.append("Unusually uniform sentence structure")
            suspicion += 0.15

    return {
        "signal": "behavioral",
        "suspicion": min(suspicion, 1.0),
        "flags": flags,
        "wps": round(wps, 2),
        "filler_count": filler_count,
    }


# ── Signal 2: Perplexity scoring ──────────────────────────────────────────────

PERPLEXITY_PROMPT = """You are evaluating whether a spoken interview answer was generated by AI or spoken naturally by a human.

Analyze the text for these AI-generation markers:
- Unnaturally smooth transitions between ideas
- Over-structured paragraphs in what should be spoken speech
- Absence of self-corrections or reformulations
- Formulaic patterns ("Firstly... Secondly... Finally...")
- Suspiciously comprehensive coverage of all sub-points
- Lacks personal voice or conversational rhythm

Rate the likelihood this was AI-generated on a scale of 0.0 to 1.0.
Respond ONLY with JSON: {"ai_probability": 0.0-1.0, "reason": "one sentence explanation"}"""

def perplexity_score(transcript: str) -> dict:
    """Uses Claude to estimate if the answer was AI-generated."""
    if not _client or len(transcript.split()) < 30:
        return {"signal": "perplexity", "suspicion": 0.0, "flags": [], "ai_probability": 0.0}

    try:
        import json
        resp = _client.messages.create(
            model="claude-sonnet-4-20250514",
            max_tokens=150,
            system=PERPLEXITY_PROMPT,
            messages=[{"role": "user", "content": f"Interview answer:\n\n{transcript}"}]
        )
        raw = resp.content[0].text.strip()
        raw = re.sub(r"```json|```", "", raw).strip()
        data = json.loads(raw)
        ai_prob = data.get("ai_probability", 0.0)
        flags = [data["reason"]] if ai_prob > 0.6 else []
        return {
            "signal": "perplexity",
            "suspicion": ai_prob,
            "flags": flags,
            "ai_probability": ai_prob,
        }
    except Exception:
        return {"signal": "perplexity", "suspicion": 0.0, "flags": [], "ai_probability": 0.0}


# ── Combined detector ─────────────────────────────────────────────────────────

def detect_cheating(
    transcript: str,
    duration_seconds: int,
    question_text: str,
) -> dict:
    """
    Combine all signals into a final cheating assessment.
    Returns: { suspicious, confidence, flags, breakdown }
    """
    b = behavioral_score(transcript, duration_seconds, question_text)
    p = perplexity_score(transcript)

    # Weighted combination: perplexity carries more weight
    combined = (b["suspicion"] * 0.4) + (p["suspicion"] * 0.6)
    all_flags = b["flags"] + p["flags"]
    suspicious = combined > 0.55

    return {
        "suspicious": suspicious,
        "confidence": round(combined, 3),
        "flags": all_flags,
        "breakdown": {
            "behavioral": round(b["suspicion"], 3),
            "perplexity": round(p["suspicion"], 3),
        }
    }
